In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from jax import config
config.update("jax_enable_x64", True)
config.update("jax_platform_name", "cpu")

import os
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"]=".8"

In [96]:
from tests.helpers import import_neuron_morph, jaxley2neuron_by_group, match_stim_loc
from jaxley.io.graph import swc_to_graph, from_graph, trace_branches, find_swc_trace_errors, simulate_swc_trace_errors, make_jaxley_compatible, add_missing_graph_attrs, split_branches, get_soma_idxs, branch_e2n, branch_n2e, insert_compartments, add_edge_lens
from jaxley.io.swc import swc_to_jaxley
from tests.helpers import import_neuron_morph, get_segment_xyzrL
import jaxley as jx
from jaxley.channels import HH
from jaxley.utils.cell_utils import v_interp

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import networkx as nx

In [107]:
graph = swc_to_graph("tests/swc_files/morph.swc")
graph = add_missing_graph_attrs(graph)

# handles special case of a single soma node
if len(soma_idxs := get_soma_idxs(graph)) == 1:
    soma = soma_idxs[0]
    # Setting l = 2*r ensures A_cylinder = 2*pi*r*l = 4*pi*r^2 = A_sphere
    graph.add_node(-1, **graph.nodes[0])
    graph.add_edge(-1, soma, l=2 * graph.nodes[soma]["r"])
    graph = nx.relabel_nodes(graph, {i: i + 1 for i in graph.nodes})

    # edges connecting nodes to soma are considered part of the soma -> l = 0.
    for i, j in (*graph.in_edges(soma), *graph.out_edges(soma)):
        graph.edges[i, j]["l"] = 0

# ensure linear root segment to ensure root branch can be created.
if graph.out_degree(0) > 1:
    graph.add_node(-1, **graph.nodes[0])
    graph.add_edge(-1, 0, l=0.1)
    graph = nx.relabel_nodes(graph, {i: i + 1 for i in graph.nodes})

graph = trace_branches(graph)

graph = insert_compartments(graph, 4)

# create subgraph w.o. edges
comp_nodes = list(nx.get_node_attributes(graph, "comp_index"))
compartment_graph = nx.subgraph(graph, comp_nodes).copy()
# remove all edges
compartment_graph.remove_edges_from(list(compartment_graph.edges))

# add inter-branch compartment edges
df = pd.DataFrame([graph.nodes[n] for n in comp_nodes])
nodes_in_branch = np.stack(df.groupby("branch_index").apply(lambda x: x.index.values))
inter_branch_edges = np.array([nodes_in_branch[:, -1][np.array(find_branch_edges(graph))[:, 0]], nodes_in_branch[:, 0][np.array(find_branch_edges(graph))[:, -1]]]).T
compartment_graph.add_edges_from(inter_branch_edges)

# add intra-branch compartment edges
df.index = comp_nodes
intra_branch_edges = df.groupby("branch_index").apply(lambda x: branch_n2e(x.index.values))
intra_branch_edges = np.stack(intra_branch_edges.values).reshape(-1, 2)
compartment_graph.add_edges_from(intra_branch_edges)

# compartment_graph = add_edge_lens(compartment_graph)

# re-enumerate in dfs from 0
mapping = {old: new for new, old in enumerate(nx.dfs_preorder_nodes(compartment_graph, 1))}
compartment_graph = nx.relabel_nodes(compartment_graph, mapping)

/tmp/ipykernel_299807/2784630246.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  nodes_in_branch = np.stack(df.groupby("branch_index").apply(lambda x: x.index.values))
/tmp/ipykernel_299807/2784630246.py:40: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  intra_branch_edges = df.groupby("branch_index").apply(lambda x: branch_n2e(x.index.values))

In [36]:
def find_branch_edges(graph: nx.DiGraph):
    """Get all linearly connected paths in a graph aka. branches.

    The graph is traversed depth-first starting from the source node.

    Args:
        graph: A networkx graph.
        source_node: node at which to start graph traversal. If "leaf", the traversal
            starts at the first identified leaf node.

    Returns:
        A list of linear paths in the graph. Each path is represented as an array of
        edges."""
    edges = []

    for i, j in nx.dfs_edges(graph, 0):
        if is_branching(graph, i):
            pre_node = next(iter(graph.predecessors(i)))
            pre_branch = graph.edges[pre_node, i]["branch_index"]
            post_branch = graph.edges[i, j]["branch_index"]
            if pre_branch != post_branch:
                edges += [(pre_branch, post_branch)]

    return edges

array([[  0,   1],
       [  2,   3],
       [  3,   4],
       [  4,   5],
       [  5,   6],
       [  6,   7],
       [  7,   8],
       [  8,   9],
       [  9,  10],
       [ 10,  11],
       [ 11,  12],
       [ 12,  13],
       [ 13,  14],
       [ 14,  15],
       [ 15,  16],
       [ 16,  17],
       [ 16,  18],
       [ 15,  19],
       [ 14,  20],
       [ 20,  21],
       [ 20,  22],
       [ 13,  23],
       [ 12,  24],
       [ 24,  25],
       [ 24,  26],
       [ 26,  27],
       [ 26,  28],
       [ 11,  29],
       [ 10,  30],
       [  9,  31],
       [  8,  32],
       [  7,  33],
       [ 33,  34],
       [ 33,  35],
       [  6,  36],
       [ 36,  37],
       [ 36,  38],
       [ 38,  39],
       [ 38,  40],
       [ 40,  41],
       [ 40,  42],
       [  5,  43],
       [ 43,  44],
       [ 43,  45],
       [ 45,  46],
       [ 45,  47],
       [ 47,  48],
       [ 47,  49],
       [  4,  50],
       [  3,  51],
       [  2,  52],
       [ 52,  53],
       [ 52,  54],
       [  0,  55],
       [ 56,  57],
       [ 57,  58],
       [ 57,  59],
       [ 59,  60],
       [ 59,  61],
       [ 61,  62],
       [ 62,  63],
       [ 62,  64],
       [ 61,  65],
       [ 65,  66],
       [ 65,  67],
       [ 56,  68],
       [ 68,  69],
       [ 69,  70],
       [ 69,  71],
       [ 71,  72],
       [ 72,  73],
       [ 72,  74],
       [ 71,  75],
       [ 68,  76],
       [ 76,  77],
       [ 77,  78],
       [ 77,  79],
       [ 76,  80],
       [ 80,  81],
       [ 81,  82],
       [ 82,  83],
       [ 82,  84],
       [ 81,  85],
       [ 80,  86],
       [  0,  87],
       [ 87,  88],
       [ 88,  89],
       [ 89,  90],
       [ 90,  91],
       [ 91,  92],
       [ 91,  93],
       [ 90,  94],
       [ 94,  95],
       [ 95,  96],
       [ 96,  97],
       [ 96,  98],
       [ 95,  99],
       [ 99, 100],
       [100, 101],
       [100, 102],
       [102, 103],
       [103, 104],
       [103, 105],
       [102, 106],
       [106, 107],
       [106, 108],
       [ 99, 109],
       [109, 110],
       [109, 111],
       [111, 112],
       [111, 113],
       [ 94, 114],
       [114, 115],
       [115, 116],
       [116, 117],
       [117, 118],
       [118, 119],
       [118, 120],
       [117, 121],
       [121, 122],
       [121, 123],
       [116, 124],
       [124, 125],
       [124, 126],
       [126, 127],
       [127, 128],
       [127, 129],
       [129, 130],
       [129, 131],
       [126, 132],
       [115, 133],
       [133, 134],
       [133, 135],
       [135, 136],
       [136, 137],
       [136, 138],
       [135, 139],
       [139, 140],
       [139, 141],
       [114, 142],
       [142, 143],
       [142, 144],
       [144, 145],
       [144, 146],
       [146, 147],
       [146, 148],
       [ 89, 149],
       [ 88, 150],
       [ 87, 151],
       [151, 152],
       [151, 153],
       [153, 154],
       [153, 155]])

In [ ]:
comp = SimpleComp()
comp.insert(HH())
comp.record()
clamp1 = -50.0 * jnp.ones((1000,))
clamp2 = -60.0 * jnp.ones((1000,))
comp.clamp("v", clamp1)

def simulate(clamp):
    data_clamps = comp.data_clamp(
        "v", clamp, None
    )  # should override the first clamp
    return jx.integrate(comp, data_clamps=data_clamps)

jitted_simulate = jax.jit(simulate)

# Clamp2 should override clamp1 here
s = jitted_simulate(clamp2)
assert np.all(s[:, 1:] == -60.0)

comp2 = SimpleComp()
comp2.insert(HH())
branch1 = jx.Branch(comp, 4)
branch2 = jx.Branch(comp2, 4)
cell = jx.Cell([branch1, branch2], [-1, -1])

# Apply the clamp1 to the second branch via clamp
cell[1, 0].clamp("v", clamp1)

# cell.delete_recordings()
# cell.branch(0).comp(0).record()
# cell.branch(1).comp(0).record()

# def simulate(clamp):
#     data_clamps = cell.branch(0).comp(0).data_clamp("v", clamp, None)
#     return jx.integrate(cell, data_clamps=data_clamps)

# jitted_simulate = jax.jit(simulate)

# # Apply clamp2 to the first branch via data_clamp
# s = jitted_simulate(clamp2)

# assert np.all(s[0, 1:] == -60.0)
# assert np.all(s[1, 1:] == -50.0)

Added 1 recordings. See `.recordings` for details.
Added 1 external_states. See `.externals` for details.
Added 1 external_states. See `.externals` for details.

In [182]:
branch_edges

[array([[0, 1]]),
 array([[1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 6],
        [6, 7],
        [7, 8],
        [8, 9]]),
 array([[ 9, 10],
        [10, 11],
        [11, 12],
        [12, 13],
        [13, 14],
        [14, 15],
        [15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 20],
        [20, 21],
        [21, 22],
        [22, 23],
        [23, 24],
        [24, 25],
        [25, 26],
        [26, 27],
        [27, 28],
        [28, 29],
        [29, 30],
        [30, 31],
        [31, 32],
        [32, 33],
        [33, 34]]),
 array([[34, 35],
        [35, 36],
        [36, 37],
        [37, 38],
        [38, 39],
        [39, 40],
        [40, 41],
        [41, 42],
        [42, 43],
        [43, 44]]),
 array([[44, 45]]),
 array([[45, 46]]),
 array([[46, 47],
        [47, 48]]),
 array([[48, 49],
        [49, 50],
        [50, 51],
        [51, 52],
        [52, 53],
        [53, 54],
        [54, 55],
        [55, 56]]),
 array([[56, 57],
        [57, 58]]),
 array([[58, 59]]),
 array([[59, 60]]),
 array([[60, 61]]),
 array([[61, 62],
        [62, 63],
        [63, 64],
        [64, 65],
        [65, 66],
        [66, 67],
        [67, 68],
        [68, 69],
        [69, 70],
        [70, 71],
        [71, 72],
        [72, 73],
        [73, 74],
        [74, 75],
        [75, 76],
        [76, 77],
        [77, 78],
        [78, 79],
        [79, 80]]),
 array([[80, 81],
        [81, 82],
        [82, 83],
        [83, 84],
        [84, 85],
        [85, 86],
        [86, 87]]),
 array([[87, 88],
        [88, 89]]),
 array([[89, 90],
        [90, 91],
        [91, 92],
        [92, 93],
        [93, 94],
        [94, 95],
        [95, 96]]),
 array([[96, 97],
        [97, 98]]),
 array([[ 98,  99],
        [ 99, 100],
        [100, 101],
        [101, 102],
        [102, 103],
        [103, 104],
        [104, 105],
        [105, 106],
        [106, 107],
        [107, 108],
        [108, 109],
        [109, 110],
        [110, 111],
        [111, 112],
        [112, 113],
        [113, 114],
        [114, 115],
        [115, 116],
        [116, 117],
        [117, 118],
        [118, 119],
        [119, 120],
        [120, 121],
        [121, 122],
        [122, 123],
        [123, 124],
        [124, 125],
        [125, 126],
        [126, 127],
        [127, 128],
        [128, 129],
        [129, 130],
        [130, 131],
        [131, 132],
        [132, 133],
        [133, 134],
        [134, 135],
        [135, 136],
        [136, 137],
        [137, 138],
        [138, 139],
        [139, 140],
        [140, 141],
        [141, 142],
        [142, 143],
        [143, 144],
        [144, 145],
        [145, 146],
        [146, 147],
        [147, 148],
        [148, 149],
        [149, 150],
        [150, 151],
        [151, 152],
        [152, 153],
        [153, 154]]),
 array([[ 98, 155],
        [155, 156],
        [156, 157],
        [157, 158],
        [158, 159],
        [159, 160],
        [160, 161],
        [161, 162],
        [162, 163],
        [163, 164],
        [164, 165],
        [165, 166],
        [166, 167],
        [167, 168],
        [168, 169],
        [169, 170],
        [170, 171],
        [171, 172],
        [172, 173],
        [173, 174],
        [174, 175],
        [175, 176],
        [176, 177],
        [177, 178],
        [178, 179],
        [179, 180],
        [180, 181],
        [181, 182],
        [182, 183],
        [183, 184],
        [184, 185],
        [185, 186],
        [186, 187],
        [187, 188],
        [188, 189],
        [189, 190],
        [190, 191],
        [191, 192],
        [192, 193],
        [193, 194],
        [194, 195],
        [195, 196],
        [196, 197],
        [197, 198],
        [198, 199],
        [199, 200],
        [200, 201],
        [201, 202],
        [202, 203],
        [203, 204]]),
 array([[ 96, 205],
        [205, 206],
        [206, 207],
        [207, 208],
        [208, 209],
        [209, 210],
        [210, 211],
        [211, 212],
        [212, 213],
        [213, 214],
        [214, 215],
        [215, 216],
        [216, 217],
        [217, 218],
        [218, 219],
        [219, 220],
        [220, 221]]),
 array([[ 89, 222],
        [222, 223],
        [223, 224],
        [224, 225],
        [225, 226],
        [226, 227],
        [227, 228]]),
 array([[228, 229],
        [229, 230],
        [230, 231],
        [231, 232],
        [232, 233],
        [233, 234],
        [234, 235],
        [235, 236],
        [236, 237],
        [237, 238],
        [238, 239],
        [239, 240],
        [240, 241],
        [241, 242],
        [242, 243],
        [243, 244],
        [244, 245],
        [245, 246],
        [246, 247],
        [247, 248]]),
 array([[228, 249],
        [249, 250],
        [250, 251],
        [251, 252],
        [252, 253],
        [253, 254],
        [254, 255],
        [255, 256],
        [256, 257],
        [257, 258],
        [258, 259],
        [259, 260],
        [260, 261],
        [261, 262],
        [262, 263],
        [263, 264],
        [264, 265],
        [265, 266],
        [266, 267],
        [267, 268],
        [268, 269],
        [269, 270],
        [270, 271],
        [271, 272],
        [272, 273],
        [273, 274],
        [274, 275]]),
 array([[ 87, 276],
        [276, 277],
        [277, 278],
        [278, 279],
        [279, 280],
        [280, 281],
        [281, 282],
        [282, 283],
        [283, 284],
        [284, 285],
        [285, 286],
        [286, 287],
        [287, 288]]),
 array([[ 80, 289],
        [289, 290],
        [290, 291],
        [291, 292],
        [292, 293],
        [293, 294],
        [294, 295],
        [295, 296],
        [296, 297],
        [297, 298]]),
 array([[298, 299],
        [299, 300],
        [300, 301],
        [301, 302],
        [302, 303],
        [303, 304],
        [304, 305],
        [305, 306],
        [306, 307],
        [307, 308],
        [308, 309],
        [309, 310],
        [310, 311],
        [311, 312],
        [312, 313],
        [313, 314],
        [314, 315],
        [315, 316],
        [316, 317],
        [317, 318],
        [318, 319],
        [319, 320],
        [320, 321],
        [321, 322],
        [322, 323],
        [323, 324],
        [324, 325],
        [325, 326],
        [326, 327],
        [327, 328],
        [328, 329],
        [329, 330],
        [330, 331],
        [331, 332],
        [332, 333],
        [333, 334],
        [334, 335],
        [335, 336],
        [336, 337],
        [337, 338],
        [338, 339],
        [339, 340],
        [340, 341],
        [341, 342],
        [342, 343],
        [343, 344],
        [344, 345],
        [345, 346],
        [346, 347],
        [347, 348],
        [348, 349],
        [349, 350],
        [350, 351],
        [351, 352],
        [352, 353]]),
 array([[298, 354],
        [354, 355],
        [355, 356],
        [356, 357],
        [357, 358],
        [358, 359],
        [359, 360],
        [360, 361],
        [361, 362],
        [362, 363],
        [363, 364],
        [364, 365],
        [365, 366],
        [366, 367],
        [367, 368],
        [368, 369],
        [369, 370],
        [370, 371],
        [371, 372],
        [372, 373],
        [373, 374],
        [374, 375],
        [375, 376],
        [376, 377],
        [377, 378],
        [378, 379],
        [379, 380],
        [380, 381],
        [381, 382],
        [382, 383],
        [383, 384],
        [384, 385],
        [385, 386],
        [386, 387],
        [387, 388]]),
 array([[388, 389],
        [389, 390],
        [390, 391],
        [391, 392],
        [392, 393],
        [393, 394],
        [394, 395],
        [395, 396],
        [396, 397],
        [397, 398],
        [398, 399],
        [399, 400],
        [400, 401],
        [401, 402],
        [402, 403],
        [403, 404],
        [404, 405],
        [405, 406],
        [406, 407],
        [407, 408],
        [408, 409],
        [409, 410]]),
 array([[388, 411],
        [411, 412],
        [412, 413],
        [413, 414]]),
 array([[ 61, 415],
        [415, 416],
        [416, 417],
        [417, 418],
        [418, 419],
        [419, 420],
        [420, 421],
        [421, 422],
        [422, 423],
        [423, 424],
        [424, 425],
        [425, 426],
        [426, 427],
        [427, 428],
        [428, 429],
        [429, 430],
        [430, 431],
        [431, 432],
        [432, 433],
        [433, 434],
        [434, 435],
        [435, 436],
        [436, 437],
        [437, 438],
        [438, 439],
        [439, 440]]),
 array([[ 60, 441],
        [441, 442],
        [442, 443],
        [443, 444],
        [444, 445],
        [445, 446],
        [446, 447],
        [447, 448],
        [448, 449],
        [449, 450],
        [450, 451],
        [451, 452],
        [452, 453],
        [453, 454],
        [454, 455],
        [455, 456],
        [456, 457],
        [457, 458],
        [458, 459],
        [459, 460],
        [460, 461],
        [461, 462]]),
 array([[ 59, 463],
        [463, 464],
        [464, 465],
        [465, 466],
        [466, 467],
        [467, 468],
        [468, 469],
        [469, 470],
        [470, 471],
        [471, 472],
        [472, 473],
        [473, 474],
        [474, 475],
        [475, 476],
        [476, 477],
        [477, 478],
        [478, 479],
        [479, 480],
        [480, 481],
        [481, 482],
        [482, 483],
        [483, 484]]),
 array([[ 58, 485],
        [485, 486],
        [486, 487],
        [487, 488],
        [488, 489],
        [489, 490],
        [490, 491],
        [491, 492],
        [492, 493],
        [493, 494],
        [494, 495],
        [495, 496],
        [496, 497],
        [497, 498],
        [498, 499],
        [499, 500],
        [500, 501]]),
 array([[ 56, 502],
        [502, 503],
        [503, 504],
        [504, 505],
        [505, 506],
        [506, 507],
        [507, 508],
        [508, 509],
        [509, 510],
        [510, 511],
        [511, 512]]),
 array([[512, 513],
        [513, 514],
        [514, 515],
        [515, 516],
        [516, 517],
        [517, 518],
        [518, 519],
        [519, 520],
        [520, 521],
        [521, 522],
        [522, 523],
        [523, 524],
        [524, 525],
        [525, 526],
        [526, 527],
        [527, 528],
        [528, 529],
        [529, 530],
        [530, 531],
        [531, 532]]),
 array([[512, 533],
        [533, 534],
        [534, 535],
        [535, 536],
        [536, 537],
        [537, 538],
        [538, 539],
        [539, 540],
        [540, 541],
        [541, 542],
        [542, 543]]),
 array([[ 48, 544],
        [544, 545]]),
 array([[545, 546],
        [546, 547],
        [547, 548],
        [548, 549],
        [549, 550],
        [550, 551],
        [551, 552],
        [552, 553],
        [553, 554],
        [554, 555],
        [555, 556],
        [556, 557],
        [557, 558],
        [558, 559],
        [559, 560],
        [560, 561],
        [561, 562],
        [562, 563],
        [563, 564],
        [564, 565],
        [565, 566],
        [566, 567],
        [567, 568]]),
 array([[545, 569],
        [569, 570],
        [570, 571],
        [571, 572],
        [572, 573],
        [573, 574],
        [574, 575],
        [575, 576]]),
 array([[576, 577],
        [577, 578],
        [578, 579],
        [579, 580],
        [580, 581],
        [581, 582],
        [582, 583],
        [583, 584],
        [584, 585]]),
 array([[576, 586],
        [586, 587],
        [587, 588],
        [588, 589],
        [589, 590],
        [590, 591],
        [591, 592],
        [592, 593],
        [593, 594],
        [594, 595],
        [595, 596]]),
 array([[596, 597],
        [597, 598],
        [598, 599],
        [599, 600]]),
 array([[596, 601],
        [601, 602],
        [602, 603],
        [603, 604],
        [604, 605],
        [605, 606],
        [606, 607],
        [607, 608],
        [608, 609],
        [609, 610],
        [610, 611],
        [611, 612],
        [612, 613],
        [613, 614],
        [614, 615],
        [615, 616],
        [616, 617],
        [617, 618],
        [618, 619]]),
 array([[ 46, 620],
        [620, 621],
        [621, 622],
        [622, 623],
        [623, 624],
        [624, 625],
        [625, 626],
        [626, 627],
        [627, 628],
        [628, 629],
        [629, 630]]),
 array([[630, 631],
        [631, 632],
        [632, 633],
        [633, 634],
        [634, 635],
        [635, 636]]),
 array([[630, 637],
        [637, 638],
        [638, 639],
        [639, 640],
        [640, 641],
        [641, 642],
        [642, 643],
        [643, 644],
        [644, 645]]),
 array([[645, 646],
        [646, 647],
        [647, 648],
        [648, 649],
        [649, 650],
        [650, 651],
        [651, 652],
        [652, 653],
        [653, 654],
        [654, 655],
        [655, 656],
        [656, 657],
        [657, 658],
        [658, 659],
        [659, 660],
        [660, 661],
        [661, 662],
        [662, 663],
        [663, 664],
        [664, 665],
        [665, 666],
        [666, 667],
        [667, 668],
        [668, 669],
        [669, 670],
        [670, 671],
        [671, 672],
        [672, 673],
        [673, 674],
        [674, 675],
        [675, 676],
        [676, 677],
        [677, 678],
        [678, 679],
        [679, 680],
        [680, 681],
        [681, 682],
        [682, 683],
        [683, 684],
        [684, 685],
        [685, 686],
        [686, 687],
        [687, 688],
        [688, 689],
        [689, 690],
        [690, 691],
        [691, 692],
        [692, 693],
        [693, 694],
        [694, 695],
        [695, 696],
        [696, 697]]),
 array([[645, 698],
        [698, 699],
        [699, 700],
        [700, 701],
        [701, 702],
        [702, 703],
        [703, 704],
        [704, 705],
        [705, 706],
        [706, 707]]),
 array([[707, 708],
        [708, 709],
        [709, 710],
        [710, 711],
        [711, 712],
        [712, 713],
        [713, 714],
        [714, 715],
        [715, 716],
        [716, 717],
        [717, 718],
        [718, 719],
        [719, 720],
        [720, 721],
        [721, 722],
        [722, 723],
        [723, 724],
        [724, 725],
        [725, 726],
        [726, 727],
        [727, 728],
        [728, 729],
        [729, 730],
        [730, 731],
        [731, 732],
        [732, 733],
        [733, 734],
        [734, 735],
        [735, 736],
        [736, 737],
        [737, 738],
        [738, 739]]),
 array([[707, 740],
        [740, 741],
        [741, 742],
        [742, 743],
        [743, 744],
        [744, 745],
        [745, 746],
        [746, 747],
        [747, 748],
        [748, 749],
        [749, 750],
        [750, 751],
        [751, 752],
        [752, 753],
        [753, 754],
        [754, 755],
        [755, 756],
        [756, 757],
        [757, 758]]),
 array([[ 45, 759],
        [759, 760],
        [760, 761],
        [761, 762],
        [762, 763],
        [763, 764],
        [764, 765],
        [765, 766],
        [766, 767],
        [767, 768],
        [768, 769],
        [769, 770],
        [770, 771]]),
 array([[ 44, 772],
        [772, 773],
        [773, 774],
        [774, 775],
        [775, 776],
        [776, 777],
        [777, 778],
        [778, 779],
        [779, 780],
        [780, 781],
        [781, 782],
        [782, 783],
        [783, 784],
        [784, 785],
        [785, 786],
        [786, 787],
        [787, 788],
        [788, 789],
        [789, 790],
        [790, 791],
        [791, 792],
        [792, 793],
        [793, 794],
        [794, 795],
        [795, 796],
        [796, 797]]),
 array([[ 34, 798],
        [798, 799],
        [799, 800],
        [800, 801],
        [801, 802],
        [802, 803],
        [803, 804],
        [804, 805],
        [805, 806],
        [806, 807],
        [807, 808],
        [808, 809],
        [809, 810],
        [810, 811],
        [811, 812],
        [812, 813],
        [813, 814],
        [814, 815],
        [815, 816],
        [816, 817],
        [817, 818],
        [818, 819],
        [819, 820],
        [820, 821],
        [821, 822]]),
 array([[822, 823],
        [823, 824],
        [824, 825],
        [825, 826],
        [826, 827],
        [827, 828],
        [828, 829],
        [829, 830],
        [830, 831],
        [831, 832],
        [832, 833],
        [833, 834],
        [834, 835],
        [835, 836],
        [836, 837],
        [837, 838],
        [838, 839]]),
 array([[822, 840],
        [840, 841],
        [841, 842],
        [842, 843],
        [843, 844],
        [844, 845],
        [845, 846],
        [846, 847],
        [847, 848],
        [848, 849],
        [849, 850],
        [850, 851]]),
 array([[  1, 852],
        [852, 853],
        [853, 854]]),
 array([[854, 855],
        [855, 856],
        [856, 857]]),
 array([[857, 858],
        [858, 859],
        [859, 860]]),
 array([[860, 861],
        [861, 862],
        [862, 863],
        [863, 864],
        [864, 865],
        [865, 866],
        [866, 867],
        [867, 868],
        [868, 869],
        [869, 870],
        [870, 871],
        [871, 872],
        [872, 873],
        [873, 874],
        [874, 875]]),
 array([[860, 876],
        [876, 877],
        [877, 878],
        [878, 879],
        [879, 880],
        [880, 881],
        [881, 882],
        [882, 883],
        [883, 884],
        [884, 885],
        [885, 886],
        [886, 887]]),
 array([[887, 888],
        [888, 889],
        [889, 890],
        [890, 891],
        [891, 892],
        [892, 893],
        [893, 894],
        [894, 895],
        [895, 896],
        [896, 897],
        [897, 898]]),
 array([[887, 899],
        [899, 900],
        [900, 901]]),
 array([[901, 902],
        [902, 903],
        [903, 904],
        [904, 905]]),
 array([[905, 906],
        [906, 907],
        [907, 908],
        [908, 909],
        [909, 910],
        [910, 911],
        [911, 912],
        [912, 913],
        [913, 914],
        [914, 915],
        [915, 916],
        [916, 917],
        [917, 918],
        [918, 919],
        [919, 920],
        [920, 921],
        [921, 922],
        [922, 923],
        [923, 924],
        [924, 925],
        [925, 926],
        [926, 927],
        [927, 928]]),
 array([[905, 929],
        [929, 930],
        [930, 931],
        [931, 932],
        [932, 933],
        [933, 934],
        [934, 935],
        [935, 936]]),
 array([[901, 937],
        [937, 938]]),
 array([[938, 939],
        [939, 940],
        [940, 941],
        [941, 942],
        [942, 943],
        [943, 944],
        [944, 945],
        [945, 946],
        [946, 947],
        [947, 948],
        [948, 949],
        [949, 950],
        [950, 951],
        [951, 952],
        [952, 953],
        [953, 954],
        [954, 955],
        [955, 956],
        [956, 957],
        [957, 958],
        [958, 959],
        [959, 960],
        [960, 961],
        [961, 962],
        [962, 963],
        [963, 964],
        [964, 965],
        [965, 966]]),
 array([[938, 967],
        [967, 968],
        [968, 969],
        [969, 970],
        [970, 971],
        [971, 972],
        [972, 973],
        [973, 974]]),
 array([[857, 975]]),
 array([[975, 976],
        [976, 977]]),
 array([[ 977,  978],
        [ 978,  979],
        [ 979,  980],
        [ 980,  981],
        [ 981,  982],
        [ 982,  983],
        [ 983,  984],
        [ 984,  985],
        [ 985,  986],
        [ 986,  987],
        [ 987,  988],
        [ 988,  989],
        [ 989,  990],
        [ 990,  991],
        [ 991,  992],
        [ 992,  993],
        [ 993,  994],
        [ 994,  995],
        [ 995,  996],
        [ 996,  997],
        [ 997,  998],
        [ 998,  999],
        [ 999, 1000],
        [1000, 1001],

In [181]:
jaxley_branches

      branch_index  node_index  id       x       y      z      r           l
0                0           0   1    0.00    0.00   0.00  8.119    0.000000
1                0           1   1    0.00    0.00   0.00  8.119    0.100000
2                1           1   1    0.00    0.00   0.00  8.119    0.000000
3                1           2   1    1.85   -4.03   0.00  7.230    4.434343
4                1           3   1    1.98   -6.00   0.00  6.280    6.408628
...            ...         ...  ..     ...     ...    ...    ...         ...
2781           155        2626   3  137.48   97.80  33.36  0.550  167.574652
2782           155        2627   3  139.56  102.04  33.36  0.550  172.297363
2783           155        2628   3  139.26  106.13  30.31  0.550  177.408194
2784           155        2629   3  138.86  112.19  44.47  0.550  192.815634
2785           155        2630   3  138.77  112.34  44.47  0.550  192.990563

[2786 rows x 8 columns]

In [151]:
jaxley_branches

      branch_index  id       x       y      z      r
0                0   1    0.00    0.00   0.00  8.119
1                0   1    0.00    0.00   0.00  8.119
2                1   1    0.00    0.00   0.00  8.119
3                1   1    1.85   -4.03   0.00  7.230
4                1   1    1.98   -6.00   0.00  6.280
...            ...  ..     ...     ...    ...    ...
2781           155   3  137.48   97.80  33.36  0.550
2782           155   3  139.56  102.04  33.36  0.550
2783           155   3  139.26  106.13  30.31  0.550
2784           155   3  138.86  112.19  44.47  0.550
2785           155   3  138.77  112.34  44.47  0.550

[2786 rows x 6 columns]

I think this is finally ready for a first round of reviews.

This has become quite the mammoth PR, but the functionality it enables is neat imo. For a rundown see the updated [08_morphologies.ipynb](https://github.com/jaxleyverse/jaxley/blob/ded457f3d55cf92e4218eefd842ce32fa8b6651b/tutorials/08_morphologies.ipynb)

All tests are passing now, which turned out to be an immense amount of work, but the imported morphologies are similar enough to NEURON both at the compartment level (x,y,z,r,l) and they also simulate correctly. I have essentially cloned the tests in `tests/test_swc.py` and added them to `tests/test_graph.py`. I have kept the tests and methods separated from everything else. The import and export functionality also works correctly.

Notable changes are:
- new `io` submodule
    - with `swc_to_graph`, `from_graph` and `to_graph` functions
    - moved `read_swc` there from `cell.py`
    - added `io.graph`
    - added `__eq__` to `Module` (I needed this to test whether re-imported modules are the same as the original.)
    - `test_graph.py` matches voltages between NEURON and Jaxley by matching compartment centers, this makes the test much more robust. Could also be added to `test_swc.py` if desired (see `tests/helpers.py`).

- Some open questions are:
    - `__eq__` is only implicitely being tested, and I dont know whether there could be a more efficient implementation
    - there is a lot of overlap between `test_graph` and `test_swc`. We could potentially move them to `tests/io/` and reduce overlap.


Lemme know your thoughts. Would also be happy to go through this in person.

In [332]:
from jaxley.utils.cell_utils import interpolate_xyz

def _update_nodes_with_xyz1(cell):
    """Add xyz coordinates to nodes."""
    loc = np.linspace(0.5 / cell.nseg, 1 - 0.5 / cell.nseg, cell.nseg)
    xyz = (
        [interpolate_xyz(loc, xyzr).T for xyzr in cell.xyzr]
        if len(loc) > 0
        else [cell.xyzr]
    )
    # idcs = cell.nodes["comp_index"]
    # cell.nodes.loc[idcs, ["x", "y", "z"]] = np.vstack(xyz)
    return np.vstack(xyz)


from jaxley.utils.cell_utils import v_interp
def _update_nodes_with_xyz2(cell):
    """Add xyz coordinates to nodes."""
    num_branches = len(cell.xyzr)
    x = np.linspace(
        0.5 / cell.nseg,
        (num_branches * 1 - 0.5 / cell.nseg),
        num_branches * cell.nseg,
    )
    x += np.arange(num_branches).repeat(
        cell.nseg
    )  # add offset to prevent branch loc overlap
    dls = [np.insert(np.cumsum(np.sqrt(np.sum(np.diff(xyzr[:,:3], axis=0) ** 2, axis=1))), 0, 0) for xyzr in cell.xyzr]
    xp = np.hstack([dl / dl.max() + 2 * i for i, dl in enumerate(dls)])
    xyz = v_interp(x, xp, np.vstack(cell.xyzr)[:, :3])
    # idcs = cell.nodes["comp_index"]
    # cell.nodes.loc[idcs, ["x", "y", "z"]] = xyz.T
    return xyz.T

graph = swc_to_graph("../tests/swc_files/morph.swc")
cell = from_graph(graph,nseg=8)

In [335]:
_update_nodes_with_xyz2(cell)

/tmp/ipykernel_2822953/3403501724.py:29: RuntimeWarning: invalid value encountered in divide
  xp = np.hstack([dl / dl.max() + 2 * i for i, dl in enumerate(dls)])

Array([[         nan,          nan,          nan],
       [         nan,          nan,          nan],
       [         nan,          nan,          nan],
       ...,
       [124.84836765,  67.02673345,  33.42886532],
       [135.52969153,  87.66895971,  33.35338212],
       [139.16860368, 107.51465421,  33.54542965]], dtype=float64)